INSERT INTO notifications (
    notification_id,
    recipient_user_id,
    category,
    kind,
    target_type,
    related_trip_id,
    title,
    message,
    created_at_utc,
    action_status,
    source_event_key,
    in_app_delivered_at_utc,
    email_delivery_status)
VALUES (
    @NotificationId,
    @RecipientUserId,
    @Category,
    @Kind,
    @TargetType,
    @RelatedTripId,
    @Title,
    @Message,
    @NowUtc,
    @ActionStatus,
    @SourceEventKey,
    @NowUtc,
    'not_requested')
ON CONFLICT (recipient_user_id, source_event_key) DO NOTHING
RETURNING notification_id AS NotificationId,
          recipient_user_id AS RecipientUserId,
          category AS Category,
          kind AS Kind,
          target_type AS TargetType,
          related_trip_id AS RelatedTripId,
          NULL::text AS RelatedTripName,
          title AS Title,
          message AS Message,
          created_at_utc AS CreatedAtUtc,
          read_at_utc AS ReadAtUtc,
          action_status AS ActionStatus,
          completed_at_utc AS CompletedAtUtc,
          completed_by_user_id AS CompletedByUserId,
          completed_by_display_name AS CompletedByDisplayName,
          email_delivery_status AS EmailDeliveryStatus;
