SELECT d.parsed_item_draft_id AS ParsedItemDraftId,
       d.inbox_email_id AS InboxEmailId,
       d.user_id AS UserId,
       d.trip_id AS TripId,
       d.trip_leg_id AS TripLegId,
       d.item_type AS ItemType,
       d.title AS Title,
       d.location AS Location,
       d.start_local AS StartLocal,
       d.start_timezone_id AS StartTimeZoneId,
       d.end_local AS EndLocal,
       d.end_timezone_id AS EndTimeZoneId,
       d.confirmation_code AS ConfirmationCode,
       d.notes AS Notes,
       d.confidence AS Confidence,
       d.review_status AS ReviewStatus,
       d.created_at_utc AS CreatedAtUtc,
       d.tracked_item_id AS TrackedItemId,
       d.proposed_outcome AS ProposedOutcome,
       d.origin AS Origin,
       d.destination AS Destination,
       d.transportation_mode AS TransportationMode,
       d.travel_cost AS TravelCost,
       d.travel_cost_currency AS TravelCostCurrency,
       d.created_trip_leg_id AS CreatedTripLegId,
       d.transport_recognition_state AS TransportRecognitionState,
       d.traveler_edited_fields AS TravelerEditedFields
FROM parsed_item_drafts d
WHERE d.user_id = @UserId
  AND d.review_status = 'pending_review'
ORDER BY d.created_at_utc DESC;
